#include "pch.hpp"
#include "input.hpp"

#include <SDL.h>

namespace engine::window::input
{
    events::MouseButtonType GetMouseButtonType(u8 sdlButton)
    {
        switch (sdlButton)
        {
            case SDL_BUTTON_LEFT:
                return events::MouseButtonType::Left;
            case SDL_BUTTON_RIGHT:
                return events::MouseButtonType::Right;
            case SDL_BUTTON_MIDDLE:
                return events::MouseButtonType::Middle;
            default:
                return events::MouseButtonType::Unknown;
        }
    }

    events::KeyCode GetKeyCode(int sdlKey)
    {
        // Compiler should generate a lookup table for this...
        switch(sdlKey)
        {
            case SDLK_RETURN:  
                return events::KeyCode::Return;
            case SDLK_ESCAPE:  
                return events::KeyCode::Escape;
            case SDLK_BACKSPACE:  
                return events::KeyCode::Backspace;
            case SDLK_TAB:  
                return events::KeyCode::Tab;
            case SDLK_SPACE:  
                return events::KeyCode::Space;
            case SDLK_EXCLAIM:  
                return events::KeyCode::Exclaim;
            case SDLK_QUOTEDBL:  
                return events::KeyCode::Quotedbl;
            case SDLK_HASH:  
                return events::KeyCode::Hash;
            case SDLK_PERCENT:  
                return events::KeyCode::Percent;
            case SDLK_DOLLAR:  
                return events::KeyCode::Dollar;
            case SDLK_AMPERSAND:  
                return events::KeyCode::Ampersand;
            case SDLK_QUOTE:  
                return events::KeyCode::Quote;
            case SDLK_LEFTPAREN:  
                return events::KeyCode::Leftparen;
            case SDLK_RIGHTPAREN:  
                return events::KeyCode::Rightparen;
            case SDLK_ASTERISK:  
                return events::KeyCode::Asterisk;
            case SDLK_PLUS:  
                return events::KeyCode::Plus;
            case SDLK_COMMA:  
                return events::KeyCode::Comma;
            case SDLK_MINUS:  
                return events::KeyCode::Minus;
            case SDLK_PERIOD:  
                return events::KeyCode::Period;
            case SDLK_SLASH:  
                return events::KeyCode::Slash;
            case SDLK_0:  
                return events::KeyCode::Key_0;
            case SDLK_1:  
                return events::KeyCode::Key_1;
            case SDLK_2:  
                return events::KeyCode::Key_2;
            case SDLK_3:  
                return events::KeyCode::Key_3;
            case SDLK_4:  
                return events::KeyCode::Key_4;
            case SDLK_5:  
                return events::KeyCode::Key_5;
            case SDLK_6:  
                return events::KeyCode::Key_6;
            case SDLK_7:  
                return events::KeyCode::Key_7;
            case SDLK_8:  
                return events::KeyCode::Key_8;
            case SDLK_9:  
                return events::KeyCode::Key_9;
            case SDLK_COLON:  
                return events::KeyCode::Colon;
            case SDLK_SEMICOLON:  
                return events::KeyCode::Semicolon;
            case SDLK_LESS:  
                return events::KeyCode::Less;
            case SDLK_EQUALS:  
                return events::KeyCode::Equals;
            case SDLK_GREATER:  
                return events::KeyCode::Greater;
            case SDLK_QUESTION:  
                return events::KeyCode::Question;
            case SDLK_AT:  
                return events::KeyCode::At;
            case SDLK_LEFTBRACKET:  
                return events::KeyCode::Leftbracket;
            case SDLK_BACKSLASH:  
                return events::KeyCode::Backslash;
            case SDLK_RIGHTBRACKET:  
                return events::KeyCode::Rightbracket;
            case SDLK_CARET:  
                return events::KeyCode::Caret;
            case SDLK_UNDERSCORE:  
                return events::KeyCode::Underscore;
            case SDLK_BACKQUOTE:  
                return events::KeyCode::Backquote;
            case SDLK_a:  
                return events::KeyCode::Key_a;
            case SDLK_b:  
                return events::KeyCode::Key_b;
            case SDLK_c:  
                return events::KeyCode::Key_c;
            case SDLK_d:  
                return events::KeyCode::Key_d;
            case SDLK_e:  
                return events::KeyCode::Key_e;
            case SDLK_f:  
                return events::KeyCode::Key_f;
            case SDLK_g:  
                return events::KeyCode::Key_g;
            case SDLK_h:  
                return events::KeyCode::Key_h;
            case SDLK_i:  
                return events::KeyCode::Key_i;
            case SDLK_j:  
                return events::KeyCode::Key_j;
            case SDLK_k:  
                return events::KeyCode::Key_k;
            case SDLK_l:  
                return events::KeyCode::Key_l;
            case SDLK_m:  
                return events::KeyCode::Key_m;
            case SDLK_n:  
                return events::KeyCode::Key_n;
            case SDLK_o:  
                return events::KeyCode::Key_o;
            case SDLK_p:  
                return events::KeyCode::Key_p;
            case SDLK_q:  
                return events::KeyCode::Key_q;
            case SDLK_r:  
                return events::KeyCode::Key_r;
            case SDLK_s:  
                return events::KeyCode::Key_s;
            case SDLK_t:  
                return events::KeyCode::Key_t;
            case SDLK_u:  
                return events::KeyCode::Key_u;
            case SDLK_v:  
                return events::KeyCode::Key_v;
            case SDLK_w:  
                return events::KeyCode::Key_w;
            case SDLK_x:  
                return events::KeyCode::Key_x;
            case SDLK_y:  
                return events::KeyCode::Key_y;
            case SDLK_z:  
                return events::KeyCode::Key_z;
            case SDLK_CAPSLOCK:  
                return events::KeyCode::Capslock;
            case SDLK_F1:  
                return events::KeyCode::F1;
            case SDLK_F2:  
                return events::KeyCode::F2;
            case SDLK_F3:  
                return events::KeyCode::F3;
            case SDLK_F4:  
                return events::KeyCode::F4;
            case SDLK_F5:  
                return events::KeyCode::F5;
            case SDLK_F6:  
                return events::KeyCode::F6;
            case SDLK_F7:  
                return events::KeyCode::F7;
            case SDLK_F8:  
                return events::KeyCode::F8;
            case SDLK_F9:  
                return events::KeyCode::F9;
            case SDLK_F10:  
                return events::KeyCode::F10;
            case SDLK_F11:  
                return events::KeyCode::F11;
            case SDLK_F12:  
                return events::KeyCode::F12;
            case SDLK_PRINTSCREEN:  
                return events::KeyCode::Printscreen;
            case SDLK_SCROLLLOCK:  
                return events::KeyCode::Scrolllock;
            case SDLK_PAUSE:  
                return events::KeyCode::Pause;
            case SDLK_INSERT:  
                return events::KeyCode::Insert;
            case SDLK_HOME:  
                return events::KeyCode::Home;
            case SDLK_PAGEUP:  
                return events::KeyCode::Pageup;
            case SDLK_DELETE:  
                return events::KeyCode::Delete;
            case SDLK_END:  
                return events::KeyCode::End;
            case SDLK_PAGEDOWN:  
                return events::KeyCode::Pagedown;
            case SDLK_RIGHT:  
                return events::KeyCode::Right;
            case SDLK_LEFT:  
                return events::KeyCode::Left;
            case SDLK_DOWN:  
                return events::KeyCode::Down;
            case SDLK_UP:  
                return events::KeyCode::Up;
            case SDLK_NUMLOCKCLEAR:  
                return events::KeyCode::Numlockclear;
            case SDLK_KP_DIVIDE:  
                return events::KeyCode::KP_Divide;
            case SDLK_KP_MULTIPLY:  
                return events::KeyCode::KP_Multiply;
            case SDLK_KP_MINUS:  
                return events::KeyCode::KP_Minus;
            case SDLK_KP_PLUS:  
                return events::KeyCode::KP_Plus;
            case SDLK_KP_ENTER:  
                return events::KeyCode::KP_Enter;
            case SDLK_KP_1:  
                return events::KeyCode::KP_1;
            case SDLK_KP_2:  
                return events::KeyCode::KP_2;
            case SDLK_KP_3:  
                return events::KeyCode::KP_3;
            case SDLK_KP_4:  
                return events::KeyCode::KP_4;
            case SDLK_KP_5:  
                return events::KeyCode::KP_5;
            case SDLK_KP_6:  
                return events::KeyCode::KP_6;
            case SDLK_KP_7:  
                return events::KeyCode::KP_7;
            case SDLK_KP_8:  
                return events::KeyCode::KP_8;
            case SDLK_KP_9:  
                return events::KeyCode::KP_9;
            case SDLK_KP_0:  
                return events::KeyCode::KP_0;
            case SDLK_KP_PERIOD:  
                return events::KeyCode::KP_Period;
            case SDLK_LCTRL:  
                return events::KeyCode::LCtrl;
            case SDLK_LSHIFT:  
                return events::KeyCode::LShift;
            case SDLK_LALT:  
                return events::KeyCode::LAlt;
            case SDLK_LGUI:  
                return events::KeyCode::LSuper;
            case SDLK_RCTRL:  
                return events::KeyCode::RCtrl;
            case SDLK_RSHIFT:  
                return events::KeyCode::RShift;
            case SDLK_RALT:  
                return events::KeyCode::RAlt;
            case SDLK_RGUI:  
                return events::KeyCode::RSuper;
            default:
                return events::KeyCode::Unknown;
        }
    }
}
