#include "pch.hpp"
#include "input/sdlKeyCodes.hpp"

#include <SDL.h>

namespace engine
{
    MouseButtonType GetMouseButtonType(u8 sdlButton)
    {
        switch (sdlButton)
        {
            case SDL_BUTTON_LEFT:
                return MouseButtonType::Left;
            case SDL_BUTTON_RIGHT:
                return MouseButtonType::Right;
            case SDL_BUTTON_MIDDLE:
                return MouseButtonType::Middle;
            default:
                return MouseButtonType::Unknown;
        }
    }

    u8 GetSDLMouseButton(MouseButtonType button)
    {
        switch (button)
        {
            case MouseButtonType::Left:
                return SDL_BUTTON_LEFT;
            case MouseButtonType::Right:
                return SDL_BUTTON_RIGHT;
            case MouseButtonType::Middle:
                return SDL_BUTTON_MIDDLE;
            default:
                return 0;
        }
    }

    KeyCode GetKeyCode(int sdlKey)
    {
        // Compiler should generate a lookup table for this...
        switch(sdlKey)
        {
            case SDLK_RETURN:  
                return KeyCode::Return;
            case SDLK_ESCAPE:  
                return KeyCode::Escape;
            case SDLK_BACKSPACE:  
                return KeyCode::Backspace;
            case SDLK_TAB:  
                return KeyCode::Tab;
            case SDLK_SPACE:  
                return KeyCode::Space;
            case SDLK_EXCLAIM:  
                return KeyCode::Exclaim;
            case SDLK_QUOTEDBL:  
                return KeyCode::Quotedbl;
            case SDLK_HASH:  
                return KeyCode::Hash;
            case SDLK_PERCENT:  
                return KeyCode::Percent;
            case SDLK_DOLLAR:  
                return KeyCode::Dollar;
            case SDLK_AMPERSAND:  
                return KeyCode::Ampersand;
            case SDLK_QUOTE:  
                return KeyCode::Quote;
            case SDLK_LEFTPAREN:  
                return KeyCode::Leftparen;
            case SDLK_RIGHTPAREN:  
                return KeyCode::Rightparen;
            case SDLK_ASTERISK:  
                return KeyCode::Asterisk;
            case SDLK_PLUS:  
                return KeyCode::Plus;
            case SDLK_COMMA:  
                return KeyCode::Comma;
            case SDLK_MINUS:  
                return KeyCode::Minus;
            case SDLK_PERIOD:  
                return KeyCode::Period;
            case SDLK_SLASH:  
                return KeyCode::Slash;
            case SDLK_0:  
                return KeyCode::Key_0;
            case SDLK_1:  
                return KeyCode::Key_1;
            case SDLK_2:  
                return KeyCode::Key_2;
            case SDLK_3:  
                return KeyCode::Key_3;
            case SDLK_4:  
                return KeyCode::Key_4;
            case SDLK_5:  
                return KeyCode::Key_5;
            case SDLK_6:  
                return KeyCode::Key_6;
            case SDLK_7:  
                return KeyCode::Key_7;
            case SDLK_8:  
                return KeyCode::Key_8;
            case SDLK_9:  
                return KeyCode::Key_9;
            case SDLK_COLON:  
                return KeyCode::Colon;
            case SDLK_SEMICOLON:  
                return KeyCode::Semicolon;
            case SDLK_LESS:  
                return KeyCode::Less;
            case SDLK_EQUALS:  
                return KeyCode::Equals;
            case SDLK_GREATER:  
                return KeyCode::Greater;
            case SDLK_QUESTION:  
                return KeyCode::Question;
            case SDLK_AT:  
                return KeyCode::At;
            case SDLK_LEFTBRACKET:  
                return KeyCode::Leftbracket;
            case SDLK_BACKSLASH:  
                return KeyCode::Backslash;
            case SDLK_RIGHTBRACKET:  
                return KeyCode::Rightbracket;
            case SDLK_CARET:  
                return KeyCode::Caret;
            case SDLK_UNDERSCORE:  
                return KeyCode::Underscore;
            case SDLK_BACKQUOTE:  
                return KeyCode::Backquote;
            case SDLK_a:  
                return KeyCode::Key_a;
            case SDLK_b:  
                return KeyCode::Key_b;
            case SDLK_c:  
                return KeyCode::Key_c;
            case SDLK_d:  
                return KeyCode::Key_d;
            case SDLK_e:  
                return KeyCode::Key_e;
            case SDLK_f:  
                return KeyCode::Key_f;
            case SDLK_g:  
                return KeyCode::Key_g;
            case SDLK_h:  
                return KeyCode::Key_h;
            case SDLK_i:  
                return KeyCode::Key_i;
            case SDLK_j:  
                return KeyCode::Key_j;
            case SDLK_k:  
                return KeyCode::Key_k;
            case SDLK_l:  
                return KeyCode::Key_l;
            case SDLK_m:  
                return KeyCode::Key_m;
            case SDLK_n:  
                return KeyCode::Key_n;
            case SDLK_o:  
                return KeyCode::Key_o;
            case SDLK_p:  
                return KeyCode::Key_p;
            case SDLK_q:  
                return KeyCode::Key_q;
            case SDLK_r:  
                return KeyCode::Key_r;
            case SDLK_s:  
                return KeyCode::Key_s;
            case SDLK_t:  
                return KeyCode::Key_t;
            case SDLK_u:  
                return KeyCode::Key_u;
            case SDLK_v:  
                return KeyCode::Key_v;
            case SDLK_w:  
                return KeyCode::Key_w;
            case SDLK_x:  
                return KeyCode::Key_x;
            case SDLK_y:  
                return KeyCode::Key_y;
            case SDLK_z:  
                return KeyCode::Key_z;
            case SDLK_CAPSLOCK:  
                return KeyCode::Capslock;
            case SDLK_F1:  
                return KeyCode::F1;
            case SDLK_F2:  
                return KeyCode::F2;
            case SDLK_F3:  
                return KeyCode::F3;
            case SDLK_F4:  
                return KeyCode::F4;
            case SDLK_F5:  
                return KeyCode::F5;
            case SDLK_F6:  
                return KeyCode::F6;
            case SDLK_F7:  
                return KeyCode::F7;
            case SDLK_F8:  
                return KeyCode::F8;
            case SDLK_F9:  
                return KeyCode::F9;
            case SDLK_F10:  
                return KeyCode::F10;
            case SDLK_F11:  
                return KeyCode::F11;
            case SDLK_F12:  
                return KeyCode::F12;
            case SDLK_PRINTSCREEN:  
                return KeyCode::Printscreen;
            case SDLK_SCROLLLOCK:  
                return KeyCode::Scrolllock;
            case SDLK_PAUSE:  
                return KeyCode::Pause;
            case SDLK_INSERT:  
                return KeyCode::Insert;
            case SDLK_HOME:  
                return KeyCode::Home;
            case SDLK_PAGEUP:  
                return KeyCode::Pageup;
            case SDLK_DELETE:  
                return KeyCode::Delete;
            case SDLK_END:  
                return KeyCode::End;
            case SDLK_PAGEDOWN:  
                return KeyCode::Pagedown;
            case SDLK_RIGHT:  
                return KeyCode::Right;
            case SDLK_LEFT:  
                return KeyCode::Left;
            case SDLK_DOWN:  
                return KeyCode::Down;
            case SDLK_UP:  
                return KeyCode::Up;
            case SDLK_NUMLOCKCLEAR:  
                return KeyCode::Numlockclear;
            case SDLK_KP_DIVIDE:  
                return KeyCode::KP_Divide;
            case SDLK_KP_MULTIPLY:  
                return KeyCode::KP_Multiply;
            case SDLK_KP_MINUS:  
                return KeyCode::KP_Minus;
            case SDLK_KP_PLUS:  
                return KeyCode::KP_Plus;
            case SDLK_KP_ENTER:  
                return KeyCode::KP_Enter;
            case SDLK_KP_1:  
                return KeyCode::KP_1;
            case SDLK_KP_2:  
                return KeyCode::KP_2;
            case SDLK_KP_3:  
                return KeyCode::KP_3;
            case SDLK_KP_4:  
                return KeyCode::KP_4;
            case SDLK_KP_5:  
                return KeyCode::KP_5;
            case SDLK_KP_6:  
                return KeyCode::KP_6;
            case SDLK_KP_7:  
                return KeyCode::KP_7;
            case SDLK_KP_8:  
                return KeyCode::KP_8;
            case SDLK_KP_9:  
                return KeyCode::KP_9;
            case SDLK_KP_0:  
                return KeyCode::KP_0;
            case SDLK_KP_PERIOD:  
                return KeyCode::KP_Period;
            case SDLK_LCTRL:  
                return KeyCode::LCtrl;
            case SDLK_LSHIFT:  
                return KeyCode::LShift;
            case SDLK_LALT:  
                return KeyCode::LAlt;
            case SDLK_LGUI:  
                return KeyCode::LSuper;
            case SDLK_RCTRL:  
                return KeyCode::RCtrl;
            case SDLK_RSHIFT:  
                return KeyCode::RShift;
            case SDLK_RALT:  
                return KeyCode::RAlt;
            case SDLK_RGUI:  
                return KeyCode::RSuper;
            default:
                return KeyCode::Unknown;
        }
    }

    int GetSDLKeyCode(KeyCode key)
    {
        switch (key)
        {
            case KeyCode::Return:
                return SDLK_RETURN; 
            case KeyCode::Escape:
                return SDLK_ESCAPE; 
            case KeyCode::Backspace:
                return SDLK_BACKSPACE; 
            case KeyCode::Tab:
                return SDLK_TAB; 
            case KeyCode::Space:
                return SDLK_SPACE; 
            case KeyCode::Exclaim:
                return SDLK_EXCLAIM; 
            case KeyCode::Quotedbl:
                return SDLK_QUOTEDBL; 
            case KeyCode::Hash:
                return SDLK_HASH; 
            case KeyCode::Percent:
                return SDLK_PERCENT; 
            case KeyCode::Dollar:
                return SDLK_DOLLAR; 
            case KeyCode::Ampersand:
                return SDLK_AMPERSAND; 
            case KeyCode::Quote:
                return SDLK_QUOTE; 
            case KeyCode::Leftparen:
                return SDLK_LEFTPAREN; 
            case KeyCode::Rightparen:
                return SDLK_RIGHTPAREN; 
            case KeyCode::Asterisk:
                return SDLK_ASTERISK; 
            case KeyCode::Plus:
                return SDLK_PLUS; 
            case KeyCode::Comma:
                return SDLK_COMMA; 
            case KeyCode::Minus:
                return SDLK_MINUS; 
            case KeyCode::Period:
                return SDLK_PERIOD; 
            case KeyCode::Slash:
                return SDLK_SLASH; 
            case KeyCode::Key_0:
                return SDLK_0; 
            case KeyCode::Key_1:
                return SDLK_1; 
            case KeyCode::Key_2:
                return SDLK_2; 
            case KeyCode::Key_3:
                return SDLK_3; 
            case KeyCode::Key_4:
                return SDLK_4; 
            case KeyCode::Key_5:
                return SDLK_5; 
            case KeyCode::Key_6:
                return SDLK_6; 
            case KeyCode::Key_7:
                return SDLK_7; 
            case KeyCode::Key_8:
                return SDLK_8; 
            case KeyCode::Key_9:
                return SDLK_9; 
            case KeyCode::Colon:
                return SDLK_COLON; 
            case KeyCode::Semicolon:
                return SDLK_SEMICOLON; 
            case KeyCode::Less:
                return SDLK_LESS; 
            case KeyCode::Equals:
                return SDLK_EQUALS; 
            case KeyCode::Greater:
                return SDLK_GREATER; 
            case KeyCode::Question:
                return SDLK_QUESTION; 
            case KeyCode::At:
                return SDLK_AT; 
            case KeyCode::Leftbracket:
                return SDLK_LEFTBRACKET; 
            case KeyCode::Backslash:
                return SDLK_BACKSLASH; 
            case KeyCode::Rightbracket:
                return SDLK_RIGHTBRACKET; 
            case KeyCode::Caret:
                return SDLK_CARET; 
            case KeyCode::Underscore:
                return SDLK_UNDERSCORE; 
            case KeyCode::Backquote:
                return SDLK_BACKQUOTE; 
            case KeyCode::Key_a:
                return SDLK_a; 
            case KeyCode::Key_b:
                return SDLK_b; 
            case KeyCode::Key_c:
                return SDLK_c; 
            case KeyCode::Key_d:
                return SDLK_d; 
            case KeyCode::Key_e:
                return SDLK_e; 
            case KeyCode::Key_f:
                return SDLK_f; 
            case KeyCode::Key_g:
                return SDLK_g; 
            case KeyCode::Key_h:
                return SDLK_h; 
            case KeyCode::Key_i:
                return SDLK_i; 
            case KeyCode::Key_j:
                return SDLK_j; 
            case KeyCode::Key_k:
                return SDLK_k; 
            case KeyCode::Key_l:
                return SDLK_l; 
            case KeyCode::Key_m:
                return SDLK_m; 
            case KeyCode::Key_n:
                return SDLK_n; 
            case KeyCode::Key_o:
                return SDLK_o; 
            case KeyCode::Key_p:
                return SDLK_p; 
            case KeyCode::Key_q:
                return SDLK_q; 
            case KeyCode::Key_r:
                return SDLK_r; 
            case KeyCode::Key_s:
                return SDLK_s; 
            case KeyCode::Key_t:
                return SDLK_t; 
            case KeyCode::Key_u:
                return SDLK_u; 
            case KeyCode::Key_v:
                return SDLK_v; 
            case KeyCode::Key_w:
                return SDLK_w; 
            case KeyCode::Key_x:
                return SDLK_x; 
            case KeyCode::Key_y:
                return SDLK_y; 
            case KeyCode::Key_z:
                return SDLK_z; 
            case KeyCode::Capslock:
                return SDLK_CAPSLOCK; 
            case KeyCode::F1:
                return SDLK_F1; 
            case KeyCode::F2:
                return SDLK_F2; 
            case KeyCode::F3:
                return SDLK_F3; 
            case KeyCode::F4:
                return SDLK_F4; 
            case KeyCode::F5:
                return SDLK_F5; 
            case KeyCode::F6:
                return SDLK_F6; 
            case KeyCode::F7:
                return SDLK_F7; 
            case KeyCode::F8:
                return SDLK_F8; 
            case KeyCode::F9:
                return SDLK_F9; 
            case KeyCode::F10:
                return SDLK_F10; 
            case KeyCode::F11:
                return SDLK_F11; 
            case KeyCode::F12:
                return SDLK_F12; 
            case KeyCode::Printscreen:
                return SDLK_PRINTSCREEN; 
            case KeyCode::Scrolllock:
                return SDLK_SCROLLLOCK; 
            case KeyCode::Pause:
                return SDLK_PAUSE; 
            case KeyCode::Insert:
                return SDLK_INSERT; 
            case KeyCode::Home:
                return SDLK_HOME; 
            case KeyCode::Pageup:
                return SDLK_PAGEUP; 
            case KeyCode::Delete:
                return SDLK_DELETE; 
            case KeyCode::End:
                return SDLK_END; 
            case KeyCode::Pagedown:
                return SDLK_PAGEDOWN; 
            case KeyCode::Right:
                return SDLK_RIGHT; 
            case KeyCode::Left:
                return SDLK_LEFT; 
            case KeyCode::Down:
                return SDLK_DOWN; 
            case KeyCode::Up:
                return SDLK_UP; 
            case KeyCode::Numlockclear:
                return SDLK_NUMLOCKCLEAR; 
            case KeyCode::KP_Divide:
                return SDLK_KP_DIVIDE; 
            case KeyCode::KP_Multiply:
                return SDLK_KP_MULTIPLY; 
            case KeyCode::KP_Minus:
                return SDLK_KP_MINUS; 
            case KeyCode::KP_Plus:
                return SDLK_KP_PLUS; 
            case KeyCode::KP_Enter:
                return SDLK_KP_ENTER; 
            case KeyCode::KP_1:
                return SDLK_KP_1; 
            case KeyCode::KP_2:
                return SDLK_KP_2; 
            case KeyCode::KP_3:
                return SDLK_KP_3; 
            case KeyCode::KP_4:
                return SDLK_KP_4; 
            case KeyCode::KP_5:
                return SDLK_KP_5; 
            case KeyCode::KP_6:
                return SDLK_KP_6; 
            case KeyCode::KP_7:
                return SDLK_KP_7; 
            case KeyCode::KP_8:
                return SDLK_KP_8; 
            case KeyCode::KP_9:
                return SDLK_KP_9; 
            case KeyCode::KP_0:
                return SDLK_KP_0; 
            case KeyCode::KP_Period:
                return SDLK_KP_PERIOD; 
            case KeyCode::LCtrl:
                return SDLK_LCTRL; 
            case KeyCode::LShift:
                return SDLK_LSHIFT; 
            case KeyCode::LAlt:
                return SDLK_LALT; 
            case KeyCode::LSuper:
                return SDLK_LGUI; 
            case KeyCode::RCtrl:
                return SDLK_RCTRL; 
            case KeyCode::RShift:
                return SDLK_RSHIFT; 
            case KeyCode::RAlt:
                return SDLK_RALT; 
            case KeyCode::RSuper:
                return SDLK_RGUI; 
            default:
                return SDLK_UNKNOWN;
        }
    }

    int GetSDLScanCode(KeyCode key)
    {
        switch (key)
        {
            case KeyCode::Return:
                return SDL_SCANCODE_RETURN; 
            case KeyCode::Escape:
                return SDL_SCANCODE_ESCAPE; 
            case KeyCode::Backspace:
                return SDL_SCANCODE_BACKSPACE; 
            case KeyCode::Tab:
                return SDL_SCANCODE_TAB; 
            case KeyCode::Space:
                return SDL_SCANCODE_SPACE; 
            case KeyCode::Quote:
                return SDL_SCANCODE_APOSTROPHE; 
            case KeyCode::Comma:
                return SDL_SCANCODE_COMMA; 
            case KeyCode::Minus:
                return SDL_SCANCODE_MINUS; 
            case KeyCode::Period:
                return SDL_SCANCODE_PERIOD; 
            case KeyCode::Slash:
                return SDL_SCANCODE_SLASH; 
            case KeyCode::Key_0:
                return SDL_SCANCODE_0; 
            case KeyCode::Key_1:
                return SDL_SCANCODE_1; 
            case KeyCode::Key_2:
                return SDL_SCANCODE_2; 
            case KeyCode::Key_3:
                return SDL_SCANCODE_3; 
            case KeyCode::Key_4:
                return SDL_SCANCODE_4; 
            case KeyCode::Key_5:
                return SDL_SCANCODE_5; 
            case KeyCode::Key_6:
                return SDL_SCANCODE_6; 
            case KeyCode::Key_7:
                return SDL_SCANCODE_7; 
            case KeyCode::Key_8:
                return SDL_SCANCODE_8; 
            case KeyCode::Key_9:
                return SDL_SCANCODE_9; 
            case KeyCode::Semicolon:
                return SDL_SCANCODE_SEMICOLON; 
            case KeyCode::Equals:
                return SDL_SCANCODE_EQUALS; 
            case KeyCode::Leftbracket:
                return SDL_SCANCODE_LEFTBRACKET; 
            case KeyCode::Backslash:
                return SDL_SCANCODE_BACKSLASH; 
            case KeyCode::Rightbracket:
                return SDL_SCANCODE_RIGHTBRACKET; 
            case KeyCode::Backquote:
                return SDL_SCANCODE_GRAVE; 
            case KeyCode::Key_a:
                return SDL_SCANCODE_A; 
            case KeyCode::Key_b:
                return SDL_SCANCODE_B; 
            case KeyCode::Key_c:
                return SDL_SCANCODE_C; 
            case KeyCode::Key_d:
                return SDL_SCANCODE_D; 
            case KeyCode::Key_e:
                return SDL_SCANCODE_E; 
            case KeyCode::Key_f:
                return SDL_SCANCODE_F; 
            case KeyCode::Key_g:
                return SDL_SCANCODE_G; 
            case KeyCode::Key_h:
                return SDL_SCANCODE_H; 
            case KeyCode::Key_i:
                return SDL_SCANCODE_I; 
            case KeyCode::Key_j:
                return SDL_SCANCODE_J; 
            case KeyCode::Key_k:
                return SDL_SCANCODE_K; 
            case KeyCode::Key_l:
                return SDL_SCANCODE_L; 
            case KeyCode::Key_m:
                return SDL_SCANCODE_M; 
            case KeyCode::Key_n:
                return SDL_SCANCODE_N; 
            case KeyCode::Key_o:
                return SDL_SCANCODE_O; 
            case KeyCode::Key_p:
                return SDL_SCANCODE_P; 
            case KeyCode::Key_q:
                return SDL_SCANCODE_Q; 
            case KeyCode::Key_r:
                return SDL_SCANCODE_R; 
            case KeyCode::Key_s:
                return SDL_SCANCODE_S; 
            case KeyCode::Key_t:
                return SDL_SCANCODE_T; 
            case KeyCode::Key_u:
                return SDL_SCANCODE_U; 
            case KeyCode::Key_v:
                return SDL_SCANCODE_V; 
            case KeyCode::Key_w:
                return SDL_SCANCODE_W; 
            case KeyCode::Key_x:
                return SDL_SCANCODE_X; 
            case KeyCode::Key_y:
                return SDL_SCANCODE_Y; 
            case KeyCode::Key_z:
                return SDL_SCANCODE_Z; 
            case KeyCode::Capslock:
                return SDL_SCANCODE_CAPSLOCK; 
            case KeyCode::F1:
                return SDL_SCANCODE_F1; 
            case KeyCode::F2:
                return SDL_SCANCODE_F2; 
            case KeyCode::F3:
                return SDL_SCANCODE_F3; 
            case KeyCode::F4:
                return SDL_SCANCODE_F4; 
            case KeyCode::F5:
                return SDL_SCANCODE_F5; 
            case KeyCode::F6:
                return SDL_SCANCODE_F6; 
            case KeyCode::F7:
                return SDL_SCANCODE_F7; 
            case KeyCode::F8:
                return SDL_SCANCODE_F8; 
            case KeyCode::F9:
                return SDL_SCANCODE_F9; 
            case KeyCode::F10:
                return SDL_SCANCODE_F10; 
            case KeyCode::F11:
                return SDL_SCANCODE_F11; 
            case KeyCode::F12:
                return SDL_SCANCODE_F12; 
            case KeyCode::Printscreen:
                return SDL_SCANCODE_PRINTSCREEN; 
            case KeyCode::Scrolllock:
                return SDL_SCANCODE_SCROLLLOCK; 
            case KeyCode::Pause:
                return SDL_SCANCODE_PAUSE; 
            case KeyCode::Insert:
                return SDL_SCANCODE_INSERT; 
            case KeyCode::Home:
                return SDL_SCANCODE_HOME; 
            case KeyCode::Pageup:
                return SDL_SCANCODE_PAGEUP; 
            case KeyCode::Delete:
                return SDL_SCANCODE_DELETE; 
            case KeyCode::End:
                return SDL_SCANCODE_END; 
            case KeyCode::Pagedown:
                return SDL_SCANCODE_PAGEDOWN; 
            case KeyCode::Right:
                return SDL_SCANCODE_RIGHT; 
            case KeyCode::Left:
                return SDL_SCANCODE_LEFT; 
            case KeyCode::Down:
                return SDL_SCANCODE_DOWN; 
            case KeyCode::Up:
                return SDL_SCANCODE_UP; 
            case KeyCode::Numlockclear:
                return SDL_SCANCODE_NUMLOCKCLEAR; 
            case KeyCode::KP_Divide:
                return SDL_SCANCODE_KP_DIVIDE; 
            case KeyCode::KP_Multiply:
                return SDL_SCANCODE_KP_MULTIPLY; 
            case KeyCode::KP_Minus:
                return SDL_SCANCODE_KP_MINUS; 
            case KeyCode::KP_Plus:
                return SDL_SCANCODE_KP_PLUS; 
            case KeyCode::KP_Enter:
                return SDL_SCANCODE_KP_ENTER; 
            case KeyCode::KP_1:
                return SDL_SCANCODE_KP_1; 
            case KeyCode::KP_2:
                return SDL_SCANCODE_KP_2; 
            case KeyCode::KP_3:
                return SDL_SCANCODE_KP_3; 
            case KeyCode::KP_4:
                return SDL_SCANCODE_KP_4; 
            case KeyCode::KP_5:
                return SDL_SCANCODE_KP_5; 
            case KeyCode::KP_6:
                return SDL_SCANCODE_KP_6; 
            case KeyCode::KP_7:
                return SDL_SCANCODE_KP_7; 
            case KeyCode::KP_8:
                return SDL_SCANCODE_KP_8; 
            case KeyCode::KP_9:
                return SDL_SCANCODE_KP_9; 
            case KeyCode::KP_0:
                return SDL_SCANCODE_KP_0; 
            case KeyCode::KP_Period:
                return SDL_SCANCODE_KP_PERIOD; 
            case KeyCode::LCtrl:
                return SDL_SCANCODE_LCTRL; 
            case KeyCode::LShift:
                return SDL_SCANCODE_LSHIFT; 
            case KeyCode::LAlt:
                return SDL_SCANCODE_LALT; 
            case KeyCode::LSuper:
                return SDL_SCANCODE_LGUI; 
            case KeyCode::RCtrl:
                return SDL_SCANCODE_RCTRL; 
            case KeyCode::RShift:
                return SDL_SCANCODE_RSHIFT; 
            case KeyCode::RAlt:
                return SDL_SCANCODE_RALT; 
            case KeyCode::RSuper:
                return SDL_SCANCODE_RGUI; 
            default:
                return SDL_SCANCODE_UNKNOWN;
        }
    }
}
